name: Test

on: [push]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: dflook/checkout@main

      - name: Check
        run: |
          if [[ -f Dockerfile ]]; then
            echo "We appear to have checkout out the repository"
          else
            echo "Checkout failed"
            exit 1
          fi
